name: "on push main"

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  JAVA_OPTS: "-Xmx4096m"
  GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false -Dorg.gradle.parallel=false'

jobs:
  build_and_upload:
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: :katalog:assembleRelease
          dependencies-cache-key: |
            **/*.gradle
            **/*.gradle.kts
            buildSrc/src/**/*.kt
            **/gradle.properties
            gradle/**
      - uses: eskatos/gradle-command-action@v1
        env:
          GITHUB_USERNAME: ${{ env.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMIT_HASH: ${{ steps.vars.outputs.sha_short }}
        with:
          arguments: :katalog:publish
          dependencies-cache-key: |
            **/*.gradle
            **/*.gradle.kts
            buildSrc/src/**/*.kt
            **/gradle.properties
            gradle/**
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: ktlintCheck
          dependencies-cache-key: |
            **/*.gradle
            **/*.gradle.kts
            buildSrc/src/**/*.kt
            **/gradle.properties
            gradle/**
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: testDebugUnitTest
          dependencies-cache-key: |
            **/*.gradle
            **/*.gradle.kts
            buildSrc/src/**/*.kt
            **/gradle.properties
            gradle/**
  deploy_docs:
    name: Deploy Docs
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: git config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: cache
        uses: actions/cache@v2
        with:
          path: docs/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn install
      - run: yarn deploy
        env:
          GIT_USER: ${{ github.actor }}:${{ github.token }}
